{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kms-secrets.serviceAccountName" . }}
  namespace: {{ include "kms-secrets.namespace" . }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
