apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yadockeri.config.name" . }}
  namespace: {{ include "yadockeri.namespace" . }}
data:
  ECHO_ENV: production
  ORGANIZATION: {{ .Values.config.github.organization }}
  POSTGRES_HOST: {{ include "db.host" . }}
  POSTGRES_DB: {{ include "db.database" . }}
---
{{- if .Values.db.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.config.name" . }}
  namespace: {{ include "yadockeri.namespace" . }}
data:
  POSTGRES_DB: {{ include "db.database" . }}
{{- end }}
