apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yadockeri.config.name" . }}
  namespace: {{ include "yadockeri.namespace" . }}
data:
  CLIENT_ID: {{ .Values.config.github.client_id | b64enc }}
  CLIENT_SECRET: {{ .Values.config.github.client_secret | b64enc }}
  SESSION_SECRET: {{ .Values.config.session_secret | b64enc }}
  POSTGRES_USER: {{ include "db.user" .  | b64enc }}
  POSTGRES_PASSWORD: {{ include "db.password" . | b64enc }}
---
{{- if .Values.db.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.config.name" . }}
  namespace: {{ include "yadockeri.namespace" . }}
data:
  POSTGRES_USER: {{ include "db.user" . | b64enc }}
  POSTGRES_PASSWORD: {{ include "db.password" . | b64enc }}
{{- end }}
