apiVersion: v1
kind: Service
metadata:
  name: {{ include "yadockeri.name" . }}
  namespace: {{ include "yadockeri.namespace" . }}
  labels:
    {{- include "yadockeri.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yadockeri.controllerLabels" . | nindent 4 }}
---
{{- if .Values.db.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.host" . }}
  namespace: {{ include "yadockeri.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "yadockeri.dbLabels" . | nindent 4 }}
{{- end }}
