{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yadockeri.serviceAccountName" . }}
  namespace: {{ include "yadockeri.namespace" . }}
  labels:
    {{- include "yadockeri.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
